[project]
name = "argsense"
version = "1.2.0a5"
description = "New command line interface based on Rich library."
authors = [{ name = "Likianta", email = "likianta@foxmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    # "lk-logger>=6.0.7",
    "neoprint>=0.1.0a28",
    "rich>=14.0.0",
]

[build-system]
requires = ["hatchling>=1.29.0"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    # "lk-utils>=3.6.0b10",
    "pyapp-window>=2.2.2",
    "streamlit>=1.56.0; python_version >= '3.12'",
    "streamlit-canary>=0.3.0a15; python_version >= '3.12'",
]

# [project.optional-dependencies]
# TODO: GUI

[project.scripts]
argsense = "argsense.__main__:cli"
argsense-cli = "argsense.__main__:cli"
argsense-gui = "argsense.__main__:gui"
argsense-tui = "argsense.__main__:tui"

[project.urls]
homepage = "https://github.com/likianta/argsense-cli"

[tool.hatch.build.targets.wheel]
packages = ["argsense"]

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.isort]
force-single-line = true
no-sections = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

# [tool.ty.rules]
# invalid-type-form = "ignore"
# unresolved-attribute = "ignore"

[tool.uv]
prerelease = "allow"

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[[tool.uv.index]]
name = "likianta"
url = "http://localhost:2191/"
explicit = true

[tool.uv.sources]
# lk-logger = { index = "likianta" }
lk-utils = { index = "likianta" }
neoprint = { index = "likianta" }
streamlit-canary = { index = "likianta" }
